spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_estagio?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root